# Generated by Django 4.1.2 on 2022-11-14 02:51

import database_models.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default=database_models.models.get_generate_book_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.TextField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
